apiVersion: v1
kind: Service
metadata:
  name: {{ include "mothership-reconciler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership-reconciler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.istioPort }}
      targetPort: {{ .Values.service.istioPort }}
      protocol: TCP
      name: istio-http
    - port: {{ .Values.fluentbit.port }}
      targetPort: fluentbit-metrics
      protocol: TCP
      name: fluentbit-metrics
  selector:
    {{- include "mothership-reconciler.selectorLabels" . | nindent 4 }}
